### ISSUE TITLE
i do not see the markings

### ISSUE THREAD

**Issue by ghost** [lolamtisch/Discord-RPC-Extension#45]
I read the response to #43 and I have looked at the wiki but, I am confused. I have
`Starting 0.1.2
WebSocket created
Connected
Recived { action: 'disconnect' }
Could not disconnect. Because not connected.
`
which then gives am error of 
`[Discord] Error #numbers #letters Error: Could not connect
    at Socket.onerror (/snapshot/Discord-RPC-Extension-0.1.2/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
`
what did I do wrong?

**Comment by lolamtisch** [comment]
You are using the desktop version of Discord, right? Not the one in the browser. Is it a modded client? And make sure you run both in the same userspace, that means don't run the client or the RPC application with admin permissions.
